### PR TITLE
Replaced Current TFM with STS in Readme.md

### PR DESCRIPTION
**Pull request by mikeconjoice**
- [X] You've read the [Contributor Guide](../CONTRIBUTING.md) and [Code of Conduct](../CODE-OF-CONDUCT.md).
- [X] You've included unit or integration tests for your change, where applicable.
- [X] You've included inline docs for your change, where applicable.

## Description
Readme.md is still referencing Current TFM when options only allow the selection of Standard-Term Support (STS)Detail 2

### CODE REVIEW

**Comment by vijayrkn** [comment]
@mikeconjoice Thank you for updating the documentation. Will approve once the description is updated.

**Comment by mikeconjoice** [comment]
> 

Thanks @vijayrkn, can you let me know what I need to add to the description please?

**Review by vijayrkn — CHANGES_REQUESTED** [review]

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/upgrade-assistant?pullRequest=1373) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/upgrade-assistant?pullRequest=1373) before we can accept your contribution.<br/><br/>:x: mikeconjoice [sign now](https://cla.dotnetfoundation.org/dotnet/upgrade-assistant?pullRequest=1373)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/upgrade-assistant?pullRequest=1373) it.</sub>

**Comment by vijayrkn** [comment]
> > 
> 
> Thanks @vijayrkn, can you let me know what I need to add to the description please?

Sorry I just realized today that I had not submitted my review. Thanks for taking care of it. Can you merge the main branch to get to the latest as well?

**Comment by mikeconjoice** [comment]
Merged from main

**Review by mikeconjoice — COMMENTED** [review]
Updated as required

**Review by vijayrkn — APPROVED** [review]

**Comment by vijayrkn** [comment]
@mikeconjoice - Thanks for your contribution.

**Pull request merged**
