### PR TITLE
Adds ArcGIS Maps SDK mappings

### PR DESCRIPTION
**Pull request by dotMorten**
- [x] You've read the [Contributor Guide](../CONTRIBUTING.md) and [Code of Conduct](../CODE-OF-CONDUCT.md).
- [ ] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [ ] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

**For PRs which target a specific extension within UA, changes won't be approved by a member of the `dotnet-upgrade-assistant-admin` group until a member of the code owners of the extension has approved, when required.**

## Description
Adds upgrade support for the[ ArcGIS Maps SDK for .NET](https://developers.arcgis.com/net/) helping Xamarin Migration to .NET MAUI

### CODE REVIEW

**Review by jstedfast — DISMISSED** [review]

**Comment by jstedfast** [comment]
The first API/Package map contribution! Exciting!

**Comment by jstedfast** [comment]
Looks like the tests failed:

```
Assert.IsFalse failed. `Esri\Esri.ArcGISRuntime.Xamarin.Forms\esri.arcgisruntime.xamarin.forms.apimap.json' - ["Esri.ArcGISRuntime.ARToolkit.Forms"]["value"] cannot be empty.
```

That's on line 17 (the NotImplemented API). Let me poke Anton about that and see if perhaps my tests are wrong or what the `value` property should be in this case.

**Comment by dotMorten** [comment]
Already fixed - The doc made me think it should be empty, but I just removed the entry.

**Comment by jstedfast** [comment]
> Already fixed - The doc made me think it should be empty, but I just removed the entry.

Excellent. I see you also fixed the other empty values. 👍

**Review by jstedfast — APPROVED** [review]

**Pull request merged**
