### PR TITLE
Make generated methods static

### PR DESCRIPTION
**Pull request by ujjwalchadha**
This PR makes the generated methods static and necessary comments so they can be called from non static contexts and from outside anything that implements a UserControl.

### CODE REVIEW

**Comment by brandonh-msft** [comment]
Looks like UTs need updating:

```
xUnit.net Console Runner v2.4.1 (64-bit .NET 6.0.7)
  Discovering: Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests
  Discovered:  Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests
  Starting:    Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests
    Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.UWPToWinAppSDKTests.ContentDialogCodeFixerTest(documentPath: "ContentDialogCaller") [FAIL]
      Assert.Equal() Failure
                                        (pos 729)
      Expected: úúúalogResult result = this.SetContentDialogRoot(saveDialog).Shoúúú
      Actual:   úúúalogResult result = /* TODO You should replace 'this' with thúúú
                                        (pos 729)
      Stack Trace:
        /_/tests/extensions/windows/Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests/UWPToWinAppSDKTests.cs(110,0): at Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.UWPToWinAppSDKTests.ContentDialogCodeFixerTest(String documentPath)
           at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
    Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.UWPToWinAppSDKTests.InitializeWithWindowTestCodeFixerTest(documentPath: "InitializeWithWindow") [FAIL]
      Assert.Equal() Failure
                                        (pos 415)
      Expected: úúú   var filePicker = this.InitializeWithWindow(new FileSavePicúúú
      Actual:   úúú   var filePicker = /* TODO You should replace 'App.WindowHanúúú
                                        (pos 415)
      Stack Trace:
        /_/tests/extensions/windows/Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests/UWPToWinAppSDKTests.cs(148,0): at Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.UWPToWinAppSDKTests.InitializeWithWindowTestCodeFixerTest(String documentPath)
           at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
  Finished:    Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests
=== TEST EXECUTION SUMMARY ===
   Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests  Total: 62, Errors: 0, Failed: 2, Skipped: 0, Time: 20.468s
=== COMMAND LINE ===
"D:\a\_work\1\s\.dotnet\dotnet.exe" exec --depsfile "D:\a\_work\1\s\artifacts\bin\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests\Debug\net6.0\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.deps.json" --runtimeconfig "D:\a\_work\1\s\artifacts\bin\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests\Debug\net6.0\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.runtimeconfig.json"  "D:\a\_work\1\s\.packages\xunit.runner.console/2.4.1/tools/netcoreapp2.0/xunit.console.dll" "D:\a\_work\1\s\artifacts\bin\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests\Debug\net6.0\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.dll" -noautoreporters -xml "D:\a\_work\1\s\artifacts\TestResults\Debug\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests_net6.0_x64.xml" -html "D:\a\_work\1\s\artifacts\TestResults\Debug\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests_net6.0_x64.html"  > "D:\a\_work\1\s\artifacts\log\Debug\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests_net6.0_x64.log" 2>&1

```

**Review by brandonh-msft — CHANGES_REQUESTED** [review]
Looks like UTs need updating:

```
xUnit.net Console Runner v2.4.1 (64-bit .NET 6.0.7)
  Discovering: Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests
  Discovered:  Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests
  Starting:    Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests
    Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.UWPToWinAppSDKTests.ContentDialogCodeFixerTest(documentPath: "ContentDialogCaller") [FAIL]
      Assert.Equal() Failure
                                        (pos 729)
      Expected: úúúalogResult result = this.SetContentDialogRoot(saveDialog).Shoúúú
      Actual:   úúúalogResult result = /* TODO You should replace 'this' with thúúú
                                        (pos 729)
      Stack Trace:
        /_/tests/extensions/windows/Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests/UWPToWinAppSDKTests.cs(110,0): at Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.UWPToWinAppSDKTests.ContentDialogCodeFixerTest(String documentPath)
           at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
    Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.UWPToWinAppSDKTests.InitializeWithWindowTestCodeFixerTest(documentPath: "InitializeWithWindow") [FAIL]
      Assert.Equal() Failure
                                        (pos 415)
      Expected: úúú   var filePicker = this.InitializeWithWindow(new FileSavePicúúú
      Actual:   úúú   var filePicker = /* TODO You should replace 'App.WindowHanúúú
                                        (pos 415)
      Stack Trace:
        /_/tests/extensions/windows/Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests/UWPToWinAppSDKTests.cs(148,0): at Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.UWPToWinAppSDKTests.InitializeWithWindowTestCodeFixerTest(String documentPath)
           at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
  Finished:    Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests
=== TEST EXECUTION SUMMARY ===
   Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests  Total: 62, Errors: 0, Failed: 2, Skipped: 0, Time: 20.468s
=== COMMAND LINE ===
"D:\a\_work\1\s\.dotnet\dotnet.exe" exec --depsfile "D:\a\_work\1\s\artifacts\bin\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests\Debug\net6.0\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.deps.json" --runtimeconfig "D:\a\_work\1\s\artifacts\bin\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests\Debug\net6.0\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.runtimeconfig.json"  "D:\a\_work\1\s\.packages\xunit.runner.console/2.4.1/tools/netcoreapp2.0/xunit.console.dll" "D:\a\_work\1\s\artifacts\bin\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests\Debug\net6.0\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests.dll" -noautoreporters -xml "D:\a\_work\1\s\artifacts\TestResults\Debug\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests_net6.0_x64.xml" -html "D:\a\_work\1\s\artifacts\TestResults\Debug\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests_net6.0_x64.html"  > "D:\a\_work\1\s\artifacts\log\Debug\Microsoft.DotNet.UpgradeAssistant.Extensions.Windows.Tests_net6.0_x64.log" 2>&1

```

**Comment by brandonh-msft** [comment]
Will approve once we get some 👀 on from one other UWP person

**Review by brandonh-msft — CHANGES_REQUESTED** [review]
Will approve once we get some 👀 on from one other UWP person

**Review by j0shuams — APPROVED** [review]

**Review by brandonh-msft — APPROVED** [review]

**Pull request merged**
