### PR TITLE
Enable CodeQL for the repo

### PR DESCRIPTION
**Pull request by vijayrkn**
- [x] You've read the [Contributor Guide](../CONTRIBUTING.md) and [Code of Conduct](../CODE-OF-CONDUCT.md).
- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for the PR that you are making. If you'd like to propose a new feature or change, please open an issue to discuss the change or find an existing issue.

## Description
Enabling CodeQL for the repo.

### CODE REVIEW

**Comment by vijayrkn** [comment]
> > @MattGal - The machines listed in the error seems to be valid based on this: [dotnet/arcade#10989 (comment)](https://github.com/dotnet/arcade/issues/10989#issue-1383225596)
> > Are there additional updates needed to keep the pipelines running?
> 
> Please review [dotnet/arcade#9895](https://github.com/dotnet/arcade/issues/9895) and ping me on Teams for any questions. This was communicated to the partners DL for some time but has caught some folks by surprise.

Thanks! Will get it updated.

**Review by MattGal — COMMENTED** [review]
Image updates look fine,but I'd note that folks tend to create a separate pipeline for codeql execution as it adds a non-trivial amount of time to every build and doesn't really need to run on every commit.

**Comment by vijayrkn** [comment]
> Image updates look fine,but I'd note that folks tend to create a separate pipeline for codeql execution as it adds a non-trivial amount of time to every build and doesn't really need to run on every commit.

Thanks! That is a good point. I will create an item to track moving these to separate pipelines for this and other related repos. For now, since the activity on this repo is not as high, it shouldn't add a lot of load on the system.

**Comment by vijayrkn** [comment]
@mjrousos / @twsouthwick - Can you please ack the PR?

**Review by twsouthwick — APPROVED** [review]

**Pull request merged**
