### PR TITLE
Remove feature flag for extension management

### PR DESCRIPTION
**Pull request by twsouthwick**

### CODE REVIEW

**Comment by sunandabalu** [comment]
can you edit the ReadMe too? I think there is reference for loose-assembly identification as experimental feature

**Comment by twsouthwick** [comment]
There's a link to the doc and I've fixed up the notice in the doc. If you see a notice on the readme let me know but I can't find one

**Comment by sunandabalu** [comment]
The loose-assembly is mentioned here, it makes sense to be called out not under experimental features anymore now that its not behind a feature flag
https://github.com/dotnet/upgrade-assistant#experimental-features

**Comment by twsouthwick** [comment]
Updated

**Review by sunandabalu — APPROVED** [review]

**Pull request merged**
