### PR TITLE
Fixes for MAUI, logging, failed step repetitions, etc.

### PR DESCRIPTION
**Pull request by mgoertz-msft**
**For PRs which target a specific extension within UA, changes won't be approved by a member of the `dotnet-upgrade-assistant-admin` group until a member of the code owners of the extension has approved, when required.**

## Description
* Allow any version of .NetStandard to be migrated to MAUI
* Avoid unnecessary TFM merges for MAUI TFM SelectorFilter
* Always show 'dotnet --info' in case of workload install failure
* Added more information to log messages, such as project names
* Added MAUI step results to SARIF output
* Prevent endless failed step repetitions by adding Failed to IsDone
* Added failure level info to SARIF output using Note as default
* Added additional optional failure details to SARIF output
* Removed about:blank default which caused empty browser windows on click
* Fixed a few grammar and spelling issues

Addresses #1359
Addresses #988

### CODE REVIEW

**Comment by mgoertz-msft** [comment]
Looking at test failures...

**Review by lutzroeder — DISMISSED** [review]

**Comment by mgoertz-msft** [comment]
@twsouthwick Looks like you may have authored the `FailedStepsAreEnumerated` test, which is failing for me now with this change (same problem in `ConfigUpdaterSubStepTests.ApplyTests`). Could you please explain the reasoning behind this test and behavior?

In my experience a failed step gets repeated endlessly in non-interactive mode, so I needed to change this behavior to fix that. Unless the step status gets reset, due to a `CurrentProject` change in the context for example, there's really no point to reselect a failed step in `GetNextStep`, is there?

**Comment by mgoertz-msft** [comment]
We discussed the failed step behavior this morning and it looks like this can be useful for interactive scenarios, so we decided to keep it as is for interactive and change it for non-interactive scenarios. I will see how/where we can best make that distinction and update the PR.

**Comment by mgoertz-msft** [comment]
@dotnet/dotnet-upgrade-assistant-admin and @dotnet/dotnet-upgrade-assistant-uwp Please review your areas of this PR. Thank you!

**Review by jstedfast — APPROVED** [review]

**Review by abpiskunov — APPROVED** [review]
:shipit:

**Pull request merged**
